#!/bin/sh

die(){
	echo "$@" ; exit
}

aclocal -I . || die "The command 'aclocal -I .' failed"
autoheader   || die "The command 'autoheader' failed"
automake     || die "The command 'automake' failed"
autoconf     || die "The command 'autoconf' failed"

